- name: Raspberry Pi Setup
  hosts: piholeGroup
  become: yes
  become_user: root
  roles:
    - role: common
    - role: raspi
    - role: docker
      tags: 
        - docker
    - role: backup
      tags: 
        - backup
    - role: smb
      tags:
        - smb
    - role: pihole
      tags:
        - pihole
