- name: Raspberry Pi Setup
  hosts: raspi
  become: yes
  become_user: root
  roles:
    - role: common
    - role: raspi
    - role: backup
      tags: 
        - backup
    - role: smb
      tags: 
        - smb
    - role: docker
      tags: 
        - docker