- name: Raspberry Pi Setup
  hosts: rutorrent
  become: yes
  become_user: root
  roles:
    - role: common
    - role: raspi
    - role: backup
      tags: 
        - backup
    - role: docker
      tags: 
        - docker
    - role: smb
      tags:
        - smb
    - role: rutorrent
      tags:
        - rutorrent