---
- name: Set up backup
  ansible.builtin.lineinfile:
    dest: "{{ backup_list }}"
    state: present
    line: "{{ item.line }}"
  loop:
    - { line: "/home/{{ docker_user_name }}/docker/rutorrent/" }
    - { line: "/home/{{ docker_user_name }}/data/" }
    - { line: "/home/{{ docker_user_name }}/passwd/" }
