---
- name: Get smb share count
  ansible.builtin.shell: "wc -l < /home/{{ smb_user_name }}/docker/samba/samba.env"
  register: smb_share_count
  changed_when: False
  check_mode: no

- name: Setup smb share
  ansible.builtin.lineinfile:
    dest: "/home/{{ smb_user_name }}/docker/samba/samba.env"
    state: present
    regexp: '^SHARE\d+=torrents;/home/{{ rutorrent_user_name }}/torrents.*'
    line: "SHARE{{ smb_share_count.stdout|int }}=torrents;/home/{{ rutorrent_user_name }}/torrents;yes;no;no;all;"
  notify: restart-docker-samba