---
- name: Get WiFi country
  ansible.builtin.command: "raspi-config nonint get_wifi_country"
  register: current_wifi_country
  changed_when: false
  ignore_errors: true #to avoid error when WiFi is not present

- name: Set wifi facts
  ansible.builtin.set_fact:
    current_wifi_country: "{{ current_wifi_country.stdout }}"
  check_mode: false
