description: "Open source network backup for Windows and Linux"
display_name: "UrBackup"
app_name: urbackup
urbackup_image: binhex/arch-urbackup:latest
traefik_endpoint: http
network_name: reverse-proxy
backup_directory: /mnt/user/backup
docker_settings_directory: /mnt/user/appdata
docker_compose_directory: /mnt/user/appdata/docker-compose
docker_compose_app_directory: /boot/config/plugins/compose.manager/projects
# best practice in unraid is to run docker containers as nobody(99):users(100)
docker_puid: 99
docker_pgid: 100
docker_timezone: Europe/Vienna
file_mask: 0644
folder_mask: 0777
icon_url: "https://forums.urbackup.org/uploads/default/original/2X/1/1051fd74d1dcbc3ad4220b43007fcab5287272b0.png"