---
- name: Get backup_user user id
  ansible.builtin.shell: "id -u {{ backup_user_user_name }}"
  register: backup_user_user_id
  changed_when: False
  check_mode: no

- name: Get backup_user user group id
  ansible.builtin.shell: "id -g {{ backup_user_user_name }}"
  register: backup_user_group_id
  changed_when: False
  check_mode: no

- name: Get backup_user user group name
  ansible.builtin.shell: "getent group {{ backup_user_group_id.stdout }} | cut -d: -f1"
  register: backup_user_group_name
  changed_when: False
  check_mode: no

- name: Set backup_user facts
  ansible.builtin.set_fact:
    backup_user_user_id: "{{ backup_user_user_id.stdout }}"
    backup_user_group_id: "{{ backup_user_group_id.stdout }}"
    backup_user_group_name: "{{ backup_user_group_name.stdout }}"
  check_mode: no