description: "Collection of Starr apps"
display_name: "Starr Apps"
app_name: starrapps
prowlarr_image: lscr.io/linuxserver/prowlarr:latest
sonarr_image: lscr.io/linuxserver/sonarr:latest
radarr_image: lscr.io/linuxserver/radarr:latest
bazarr_image: lscr.io/linuxserver/bazarr:latest
recyclarr_image: recyclarr/recyclarr:latest 
traefik_endpoint: http
network_name: reverse-proxy
docker_settings_directory: /mnt/user/appdata
docker_media_share: /mnt/user/media
docker_usenet_share: /mnt/user/usenet
docker_torrent_share: /mnt/user/torrents
docker_compose_directory: /mnt/user/appdata/docker-compose
docker_compose_app_directory: /boot/config/plugins/compose.manager/projects
docker_puid: 1000
docker_pgid: 1000
docker_timezone: Europe/Vienna
file_mask: 0644
folder_mask: 0777
recyclarr_schedule: "@daily"