description: "An all-in-one anime manager"
display_name: "Shoko Server"
app_name: shokoserver
traefik_endpoint: http
network_name: reverse-proxy
docker_settings_directory: /mnt/user/appdata
docker_media_share: /mnt/user/media
docker_usenet_share: /mnt/user/usenet
docker_torrent_share: /mnt/user/torrents
docker_compose_directory: /mnt/user/appdata/docker-compose
docker_compose_app_directory: /boot/config/plugins/compose.manager/projects
docker_puid: 1000
docker_pgid: 1000
docker_timezone: Europe/Vienna
file_mask: 0644
folder_mask: 0777
icon_url: "https://raw.githubusercontent.com/ShokoAnime/ShokoDocs/master/static/icon.png"