---
- import_tasks: set-hostname.yml
  tags:
    - baseconfig
    - hostname

- import_tasks: set-locale.yml
  tags:
    - baseconfig
    - locale

- import_tasks: set-bootconfig.yml
  tags:
    - baseconfig
    - bootconfig

- import_tasks: create-user.yml
  tags:
    - baseconfig
    - user

- import_tasks: secure-ssh.yml
  tags:
    - baseconfig
    - securessh

- name: Run apt upgrade
  include_role:
    name: common
    tasks_from: apt-upgrade
  tags: 
    - baseconfig
    - software


- import_tasks: config-backup.yml
  tags:
    - baseconfig
    - backup

# TODO
# configure smb
# backup solution sudo su pibackup; crontab -l
