---
- ansible.builtin.import_tasks: set-locale.yml
  tags:
    - baseconfig
    - locale

- ansible.builtin.import_tasks: set-bootconfig.yml
  tags:
    - baseconfig
    - bootconfig

- ansible.builtin.import_tasks: create-user.yml
  tags:
    - baseconfig
    - user

- ansible.builtin.import_tasks: secure-ssh.yml
  tags:
    - baseconfig
    - securessh

- name: Upgrade packages
  ansible.builtin.apt:
    update_cache: true
    autoclean: true
    autoremove: true
    upgrade: dist
    cache_valid_time: 86400
  tags:
    - baseconfig
    - upgrade
  notify: reboot
