---
- import_tasks: set-hostname.yml
  tags:
    - baseconfig
    - hostname

- import_tasks: set-locale.yml
  tags:
    - baseconfig
    - locale

- import_tasks: set-bootconfig.yml
  tags:
    - baseconfig
    - bootconfig

- import_tasks: create-user.yml
  tags:
    - baseconfig
    - user

- import_tasks: secure-ssh.yml
  tags:
    - baseconfig
    - securessh

- name: Upgrade packages
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    upgrade: dist
    cache_valid_time: 86400
  tags: 
    - baseconfig
    - upgrade
  notify: reboot


