---
- name: Secure SSH
  block:
    - name: Update loopback hosts entry
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        state: present
        regexp: '^127\.0\.1\.1.*'
        line: "127.0.1.1 {{ inventory_hostname }}"
        
    - name: Disallow password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present

    - name: Disable root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present

    - name: Remove pi user
      ansible.builtin.user:
        name: pi
        state: absent
        remove: true

  notify: reboot