description: "A download schdeduler for NzbHydra"
display_name: "NzbHydra Scheduler"
app_name: nzbhydrascheduler
nzbhydra_scheduler_image: mmuffins/nzbhydra-scheduler:latest
traefik_endpoint: http
network_name: reverse-proxy
docker_settings_directory: /mnt/user/appdata
docker_media_share: /mnt/user/media
docker_usenet_share: /mnt/user/usenet
docker_torrent_share: /mnt/user/torrents
docker_compose_directory: /mnt/user/appdata/docker-compose
docker_compose_app_directory: /boot/config/plugins/compose.manager/projects
docker_puid: 1000
docker_pgid: 1000
docker_timezone: Europe/Vienna
file_mask: 0644
folder_mask: 0777
icon_url: "https://raw.githubusercontent.com/theotherp/nzbhydra2/master/core/ui-src/img/favicon96.png"

nzbschedule_cron: 0 2 */3 * *
nzbschedule_search_cooldown: "72"
nzbschedule_loglevel: debug
nzbschedule_searchtermsfile: /config/searchterms
nzbschedule_groupsfile: /config/groups
nzbschedule_showsfile: /config/shows
nzbschedule_output_directory: /output
nzbschedule_minsize: 1
nzbschedule_maxsize: 900000
nzbschedule_maxage: 3
nzbschedule_category: Anime
nzbschedule_indexers: Animetosho
nzbschedule_request_cooldown: 10
nzbhydra_uri: nzbhydra:5076
nzbhydra_api_key: 