---
description: "Syncthing node for local Obsidian sync."
display_name: "Syncthing"
app_name: syncthing
syncthing_image: syncthing/syncthing:2
traefik_endpoint: http
network_name: reverse-proxy
docker_settings_directory: /mnt/user/appdata
docker_compose_directory: /mnt/user/appdata/docker-compose
docker_compose_app_directory: /boot/config/plugins/compose.manager/projects
docker_puid: 1000
docker_pgid: 1000
docker_timezone: Europe/Vienna
file_mask: 0644
folder_mask: 0777
icon_url: "https://syncthing.net/img/syncthing-logo-512.png"
syncthing_default_umask: "002"
syncthing_disable_default_folder: true
syncthing_gui_port: 8384
syncthing_sync_port: 22000
syncthing_quic_port: 22000
syncthing_discovery_port: 21027
