---
- name: Get docker user id
  ansible.builtin.shell: "id -u {{ docker_user_name }}"
  register: docker_user_id
  changed_when: False
  check_mode: no

- name: Get docker user group id
  ansible.builtin.shell: "id -g {{ docker_user_name }}"
  register: docker_group_id
  changed_when: False
  check_mode: no

- name: Get docker user group name
  ansible.builtin.shell: "getent group {{ docker_group_id.stdout }} | cut -d: -f1"
  register: docker_group_name
  changed_when: False
  check_mode: no

- name: Set docker facts
  ansible.builtin.set_fact:
    docker_user_id: "{{ docker_user_id.stdout }}"
    docker_group_id: "{{ docker_group_id.stdout }}"
    docker_group_name: "{{ docker_group_name.stdout }}"
  check_mode: no