---
- name: reboot
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

- name: update-locale
  command: "update-locale LANG={{ system_locale }}"

- name: restart-docker-samba
  community.docker.docker_compose:
    state: present
    pull: true
    project_src: "/home/{{ smb_user_name }}/docker/samba"
  become: yes
  become_user: "{{ smb_user_name }}"
  register: smb_docker_output