---
- name: reboot
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

- name: update-locale
  command: "update-locale LANG={{ system_locale }}"
  
- name: restart-docker
  service: 
    name: docker 
    state: restarted