description: "A meta search for NZB indexers"
display_name: "NZBHydra"
app_name: nzbhydra
traefik_endpoint: http
network_name: reverse-proxy
docker_settings_directory: /mnt/user/appdata
docker_media_data_share: /mnt/user/data
docker_compose_directory: /mnt/user/appdata/docker-compose
docker_compose_app_directory: /boot/config/plugins/compose.manager/projects
docker_puid: 1000
docker_pgid: 1000
docker_timezone: Europe/Vienna
file_mask: 0644
folder_mask: 0775
icon_url: "https://raw.githubusercontent.com/theotherp/nzbhydra2/master/core/ui-src/img/favicon96.png"