---
- name: Create docker compose app folder
  ansible.builtin.file:
    state: directory
    path: "{{ docker_compose_app_directory }}/{{ app_name }}"
    mode: "{{ folder_mask }}"

# running it twice is easier than having to figure out how to work around initial
# permission errors when creating the folder
- name: Create docker compose folder
  ansible.builtin.file:
    state: directory
    path: "{{ docker_compose_directory }}/{{ app_name }}"
    owner: "{{ docker_puid }}"
    group: "{{ docker_pgid }}"
    mode: "{{ folder_mask }}"

- name: Set docker compose app name
  ansible.builtin.lineinfile:
    dest: "{{ docker_compose_app_directory }}/{{ app_name }}/name"
    create: true
    state: present
    regexp: '.*'
    line: "{{ display_name }}"

- name: Set docker compose app description
  ansible.builtin.lineinfile:
    dest: "{{ docker_compose_app_directory }}/{{ app_name }}/description"
    create: true
    state: present
    regexp: '.*'
    line: "{{ description }}"

- name: Set docker compose app redirection
  ansible.builtin.lineinfile:
    dest: "{{ docker_compose_app_directory }}/{{ app_name }}/indirect"
    create: true
    state: present
    line: "{{ docker_compose_directory }}/{{ app_name }}"
  register: app_redirection

- name: Remove docker compose redirection file line ending
  ansible.builtin.replace:
    path: "{{ docker_compose_app_directory }}/{{ app_name }}/indirect"
    regexp: "\n"
    replace: ""
  when: app_redirection.changed == 1
  changed_when: false
  check_mode: false

- name: Create settings folder
  ansible.builtin.file:
    state: directory
    path: "{{ docker_settings_directory }}/{{ app_name }}"
    owner: "{{ docker_puid }}"
    group: "{{ docker_pgid }}"
    mode: "{{ folder_mask }}"

- name: Create config subfolder
  ansible.builtin.file:
    state: directory
    path: "{{ docker_settings_directory }}/{{ app_name }}/config"
    owner: "{{ docker_puid }}"
    group: "{{ docker_pgid }}"
    mode: "{{ folder_mask }}"

- name: Create docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_directory }}/{{ app_name }}/docker-compose.yml"
    owner: "{{ docker_puid }}"
    group: "{{ docker_pgid }}"
    mode: "{{ file_mask }}"
  register: created_docker_compose
