---
- name: Run apt update
  apt:
    update_cache: yes

- name: Remove unneeded packages
  apt:
    autoclean: yes

- name: Remove unneeded dependencies
  apt:
    autoremove: yes

- name: Run apt dist-upgrade
  apt:
    upgrade: dist
