description: "The Prometheus monitoring system and time series database"
display_name: "Prometheus"
app_name: prometheus
prometheus_image: prom/prometheus:latest
traefik_endpoint: http
network_name: reverse-proxy
docker_compose_directory: /mnt/user/appdata/docker-compose
docker_compose_app_directory: /boot/config/plugins/compose.manager/projects
docker_settings_directory: /mnt/user/appdata
prometheus_retention_time: 15d
docker_puid: 1000
docker_pgid: 1000
docker_timezone: Europe/Vienna
file_mask: 0644
folder_mask: 0777
icon_url: "https://prometheus.io/assets/favicons/apple-touch-icon-76x76.png"