---
- import_tasks: facts.yml

# Not required for docker directly, but to set permissions needed to impersonate the user that
# will run docker, see https://github.com/georchestra/ansible/issues/55
- name: Install required packaged
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - acl

- name: Create docker folder
  ansible.builtin.file:
    state: directory
    path: "/home/{{ smb_user_name }}/docker/samba"
    owner: "{{ smb_user_name }}"
    group: "{{ smb_group_name }}"
    mode: 0770

- name: Create docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "/home/{{ smb_user_name }}/docker/samba/docker-compose.yml"
    mode: 0644
    owner: "{{ smb_user_id }}"
    group: "{{ smb_group_id }}"

- name: Create shares env file
  ansible.builtin.file:
    state: touch
    path: "/home/{{ smb_user_name }}/docker/samba/samba.env"
    owner: "{{ smb_user_name }}"
    group: "{{ smb_group_name }}"
    mode: 0644
    modification_time: preserve
    access_time: preserve

- name: Setup default share
  ansible.builtin.lineinfile:
    dest: "/home/{{ smb_user_name }}/docker/samba/samba.env"
    state: present
    line: "{{ item.line }}"
  loop:
    - { line: "SHARE=home;/home;yes;no;no;all;" }

- name: Start container
  community.docker.docker_compose:
    state: present
    pull: true
    project_src: "/home/{{ smb_user_name }}/docker/samba"
  become: yes
  become_user: "{{ smb_user_name }}"
  register: smb_docker_output

- name: Prune docker images
  community.docker.docker_prune:
    containers: yes
    networks: yes
    volumes: yes
    images: yes
    images_filters:
      dangling: false